# -*- mode: ruby -*-
# vi: set ft=ruby :

### This version is working needed the correct box with Network Manager disabled ###
# We set the last octet in IPV4 address here
nodes = {
 'master' => [1, 120],
 'node1' => [1, 121],
 'node2' => [1, 122],
}

Vagrant.configure("2") do |config| 
  # Virtualbox
  config.vm.box = "bento/centos-7.4"

   # Proxies (set in top level Vagrantfile)
   #config.proxy.http     = "http://proxy-chain.intel.com:911"
   #config.proxy.https    = "https://proxy-chain.intel.com:912"
   #config.proxy.no_proxy = "localhost, 127.0.0.1, 172.10.0.0, 172.16.0.0"

  # Default is 2200..something, but port 2200 is used by forescout NAC agent.
  config.vm.usable_port_range= 2800..2900

  nodes.each do |prefix, (count, ip_start)|
    count.times do |i|
      hostname = "%s" % [prefix, (i+1)]

      config.vm.define "#{hostname}" do |box|
        box.vm.hostname = "#{hostname}"
        box.vm.network :private_network, ip: "172.10.0.#{ip_start+i}", :netmask => "255.255.255.0"
        box.vm.network :private_network, ip: "172.16.0.#{ip_start+i}", :netmask => "255.255.255.0" 
        #box.vm.network :private_network, ip: "192.168.100.#{ip_start+i}", :netmask => "255.255.255.0"
        box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 512]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        end # box.vm
      end # config.vm.define 
    end # count.times
    # Per node tasks

  end # nodes.each
  # Add global tasks here

  # Do some provisioning
  config.vm.provision "shell", inline: <<-SHELL
    
  SHELL

end # Vagrant.configure("2")
