# -*- mode: ruby -*-
# vi: set ft=ruby :
### Multi node example
### Creates 3 VMs from the "nodes" hash
### Example of using a hash created in the Vagrant file and setting IP from a hash value

# We set the last octet in IPV4 address here
nodes = {
 'master' => [1, 120],
 'node1' => [1, 121],
 'node2' => [1, 122],
}

Vagrant.configure("2") do |config| 
  # Virtualbox
  config.vm.box = "bento/centos-7.4"

  # Default is 2200..something, but port 2200 is used by forescout NAC agent.
  config.vm.usable_port_range= 2800..2900

  nodes.each do |prefix, (count, ip_start)|
    count.times do |i|
      hostname = "%s" % [prefix, (i+1)]

      config.vm.define "#{hostname}" do |box|
        box.vm.hostname = "#{hostname}"
        box.vm.network :private_network, ip: "172.10.0.#{ip_start+i}", :netmask => "255.255.255.0"
        box.vm.network :private_network, ip: "172.16.0.#{ip_start+i}", :netmask => "255.255.255.0" 

        box.vm.provider :virtualbox do |vb|
          # Old example - no alias for memory and CPU then
          vb.customize ["modifyvm", :id, "--memory", 512]
          vb.customize ["modifyvm", :id, "--cpus", 1]
        end # box.vm

      end # config.vm.define 

    end # count.times

  end # nodes.each
  
  ### Add global tasks done on every node here

  # Do some provisioning
  config.vm.provision "shell", inline: <<-SHELL
    echo "Shell Provisioner Placeholder"
  SHELL

end # Vagrant.configure("2")
