# -*- mode: ruby -*-
# # vi: set ft=ruby :
# Simple Vangrantfile
# Created By: Karl Vietmeier

###- Bare Minimum
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"
 

# Ignore built-in Windows SSH client (doesn't seem to work)
VAGRANT_PREFER_SYSTEM_BIN=0

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.forward_agent = true

end