# -*- mode: ruby -*-
# # vi: set ft=ruby :
# Simple Vangrantfile
# Created By: Karl Vietmeier

###- Bare Minimum
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  #config.vm.box = "centos/7"
  config.vm.box = "generic/rhel7"

end