# -*- mode: ruby -*-
# vi: set ft=ruby :
# The Vagrant ClearLinux plugin is required:
# https://github.com/AntonioMeireles/vagrant-guests-clearlinux

Vagrant.configure(2) do |config|
  config.vm.box = "AntonioMeireles/ClearLinux"
  config.vm.hostname = "clearlinux"
  config.vm.usable_port_range= 2800..2900
  config.vm.network "private_network", ip: "172.16.0.220"
  config.vm.network "private_network", ip: "172.10.0.220"

  config.vm.provider "virtualbox" do |vb|
   vb.memory = "512"
  end # end Provider

end # end configure(2)
