# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  #config.ssh.insert_key=false
  config.vm.box_check_update = false
  config.vm.network "public_network"

  # Work around failed folder mount
  #config.vm.synced_folder ".", "/vagrant", type:"smb", mount_options: ["vers=3.0"]
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Some HyperV secific settings
  config.vm.provider "hyperv" do |hv|
     # Customize the amount of memory on the VM:
     hv.memory = "1024"
     hv.differencing_disk = true
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
