# -*- mode: ruby -*-
# vi: set ft=ruby :
# Setup VM with multiple disks
# Created By: Karl Vietmeier
# Test environment for adding multiple disks to a guest

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
    # Hostname
    config.vm.hostname = "multidisk"
    config.vm.usable_port_range = 2800..2900
    config.vm.box_check_update  = false
 
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    config.vm.network "private_network", ip: "172.16.0.201"
    config.vm.network "private_network", ip: "172.10.0.201"
    config.vm.network "forwarded_port", guest: 22, host: 2910
 
    # Configure/Provision VMs
    config.vm.provider "virtualbox" do |vb|
    
      # VM customization - strip out useless devices and turn ioapic 
      vb.name = "multidisk"
      vb.customize ["modifyvm", :id, "--ioapic", "on" ]
      vb.customize ["modifyvm", :id, "--memory", "512" ]
      vb.customize ["modifyvm", :id, "--cpus", "1" ]
      vb.customize ["modifyvm", :id, "--audio", "none" ]
      vb.customize ["modifyvm", :id, "--usb", "off" ]

      # Add SATA controller - you can only have one
      vb.customize ['storagectl', :id, '--name',  'SATA Controller', '--add', 'sata',  '--controller', 'IntelAhci', '--portcount', 8]

      # Loop and create/attach the extra disks
      (1..3).each do |num|

        # Create OSD drive/s 
        unless File.exist?("Disk-0#{num}.vdi")
        vb.customize ['createhd', '--filename', "Disk-0#{num}.vdi", '--size', 512]
        end  # End create disk

        # Attach the drive to the controller
        vb.customize [ 'storageattach', :id, '--storagectl', 'SATA Controller', '--port', "#{num}", '--device', 0, '--type', 'hdd', '--medium', "./Disk-0#{num}.vdi"]

      end # Create/attach disks  
    
      unless File.exist?("small_disk.vdi")
        vb.customize ['createhd', '--filename', "small_disk.vdi", '--size', 256]
      end  # End journal create disk

      vb.customize [ 'storageattach', :id, '--storagectl', 'SATA Controller', '--port', 6, '--device', 0, '--type', 'hdd', '--medium', "./small_disk.vdi"]

    end # End Provider
   
    # Copy in the hosts file
    config.vm.provision "file", source: "../../scripts/env/hosts", destination: "~/hosts"
      
end
