# -*- mode: ruby -*-
# vi: set ft=ruby :
# Created By: Karl Vietmeier
# Basic Vagrantfile for the Azure provider
# https://www.rubydoc.info/gems/vagrant-azure/1.3.0

###--- Vars
# Path to the local users public key file in $HOME/.ssh
# We use it later in the shell provisioner to populate authorized_keys
ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
adminvm_karlvkey = File.readlines("#{Dir.home}/Documents/Projects/vagrant/certs/adminvm_karlv_id_rsa.pub").first.strip
adminvm_rootkey = File.readlines("#{Dir.home}/Documents/Projects/vagrant/certs/adminvm_root_id_rsa.pub").first.strip
wslsshkey = File.readlines("#{Dir.home}/Documents/Projects/vagrant/certs/wslsshkey_id_rsa.pub").first.strip


###--- Main block
Vagrant.configure('2') do |config|
  config.vm.box = 'azure'

  config.vm.provider :azure do |azure, override|
    ###--- Mandatory Settings 
    azure.mgmt_certificate = 'YOUR AZURE MANAGEMENT CERTIFICATE'
    azure.subscription_id = 'YOUR AZURE SUBSCRIPTION ID'
    azure.mgmt_endpoint = 'https://management.core.windows.net'
    azure.vm_image = 'NAME OF THE IMAGE TO USE'
    # max 15 characters. contains letters, number and hyphens. can start with letters and can end with letters and numbers
    azure.vm_name = 'vagrant01'
    # vm_password is optional when specifying the private_key_file with Linux VMs
    # When building a Windows VM and using WinRM this setting is used to authenticate via WinRM (PowerShell Remoting)
    azure.vm_password = 'Pass@word123'

    ###--- Optional Settings
    # A new one will be generated if not provided.
    azure.storage_acct_name = 'vagrant_stor'
    # Defaults to 'vagrant' if not provided
    azure.vm_user = 'vagrant'
    # Same as vm_name. leave blank to auto-generate
    azure.cloud_service_name = 'Vagrant' 
    # Defaults to cloud_service_name 
    azure.deployment_name = 'Vagrant' 
    # e.g., West US
    azure.vm_location = 'West US'

    ###--- Optional *Nix Settings
    azure.ssh_port = 'A VALID PUBLIC PORT' # defaults to 22
    azure.private_key_file = 'Path to your ssh private key file (~/.ssh/id_rsa) to use for passwordless auth. If the id_rsa file is password protected, you will be prompted for the password.'

    ###--- Optional Windows Settings
    azure.winrm_transport = [ 'http', 'https' ] # this will open up winrm ports on both http (5985) and http (5986) ports
    azure.winrm_https_port = 'A VALID PUBLIC PORT' # customize the winrm https port, instead of 5986
    azure.winrm_http_port = 'A VALID PUBLIC PORT' # customize the winrm http port, insted of 5985
    azure.tcp_endpoints = '3389:53389' # opens the Remote Desktop internal port that listens on public port 53389. Without this, you cannot RDP to a Windows VM.
  end
end